# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGqelR3mkgKN-jx23E0iIT6ygAEmfImX
"""

import pandas as pd
data = {
    'Ism': ['Ali', 'Vali', 'Sardor'],
    'Yoshi': [25, 30, 22],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro']
}
df = pd.DataFrame(data)
print(df)
young_people = df[df['Yoshi'] < 30]
print("30 yoshdan kichiklar:\n", young_people)


df['Yoshi'] += 1
print("Yangilangan DataFrame:\n", df)
df.to_csv('data.csv', index=False)